# Generated by Django 5.1.7 on 2025-03-25 20:14

from django.db import migrations
from django.utils.text import slugify


def create_initial_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model("stories", "Category")

    # Define common story categories
    categories = [
        {
            "name": "Fantasy",
            "slug": "fantasy",
            "description": "Stories involving magical or supernatural elements, often set in imaginary worlds.",
        },
        {
            "name": "Science Fiction",
            "slug": "science-fiction",
            "description": "Speculative fiction that deals with imaginative concepts such as futuristic technology, space exploration, and time travel.",
        },
        {
            "name": "Mystery",
            "slug": "mystery",
            "description": "Stories that revolve around solving a crime, puzzle, or unexplained phenomenon.",
        },
        {
            "name": "Romance",
            "slug": "romance",
            "description": "Stories that focus on relationships and romantic love between characters.",
        },
        {
            "name": "Horror",
            "slug": "horror",
            "description": "Stories intended to frighten, scare, or startle through inducing feelings of horror and terror.",
        },
        {
            "name": "Thriller",
            "slug": "thriller",
            "description": "Fast-paced, suspenseful stories designed to keep readers on the edge of their seats.",
        },
        {
            "name": "Drama",
            "slug": "drama",
            "description": "Character-driven narratives focusing on realistic scenarios and emotional themes.",
        },
        {
            "name": "Comedy",
            "slug": "comedy",
            "description": "Stories with humorous elements, designed to amuse and entertain.",
        },
        {
            "name": "Action/Adventure",
            "slug": "action-adventure",
            "description": "Stories featuring exciting, risky, or dangerous undertakings and physical feats.",
        },
        {
            "name": "Historical Fiction",
            "slug": "historical-fiction",
            "description": "Stories set in the past, often inspired by real historical events or periods.",
        },
        {
            "name": "Young Adult",
            "slug": "young-adult",
            "description": "Stories targeting teenage and young adult readers, often dealing with themes of identity and growing up.",
        },
        {
            "name": "Children's",
            "slug": "childrens",
            "description": "Stories written for children, often with simpler language and moral lessons.",
        },
        {
            "name": "Biography",
            "slug": "biography",
            "description": "True accounts of a person's life, written by someone else.",
        },
        {
            "name": "Memoir",
            "slug": "memoir",
            "description": "A narrative based on the author's personal experiences.",
        },
        {
            "name": "Poetry",
            "slug": "poetry",
            "description": "Works characterized by the use of a concentrated imaginative awareness of experience or a specific emotional response.",
        },
        {
            "name": "Essay",
            "slug": "essay",
            "description": "Short literary compositions that reflect the author's outlook or point of view.",
        },
        {
            "name": "Flash Fiction",
            "slug": "flash-fiction",
            "description": "Extremely short stories, typically under 1000 words.",
        },
        {
            "name": "Fan Fiction",
            "slug": "fan-fiction",
            "description": "Fiction written by fans of a particular work, featuring characters or settings from the original.",
        },
        {
            "name": "Supernatural",
            "slug": "supernatural",
            "description": "Stories featuring paranormal elements like ghosts, vampires, or werewolves.",
        },
        {
            "name": "Dystopian",
            "slug": "dystopian",
            "description": "Stories set in imagined societies where there is great suffering or injustice.",
        },
    ]

    # Create each category
    for category_data in categories:
        Category.objects.create(**category_data)


def remove_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model("stories", "Category")

    # Delete all categories
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_categories),
    ]
