# Generated by Django 5.1.7 on 2025-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_add_initial_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
